// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJXM1KUxD7_lo-fy8NSSuGzKW0GwGE-tU',
    appId: '1:224865790377:web:fe98eed759ac10f0477cb8',
    messagingSenderId: '224865790377',
    projectId: 'heardattack2',
    authDomain: 'heardattack2.firebaseapp.com',
    storageBucket: 'heardattack2.firebasestorage.app',
    measurementId: 'G-9RKHRGHCL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMjEXm3ve7Y6PU2EG_qoGNh1NE8NaPb8',
    appId: '1:224865790377:android:2212f1a24942b493477cb8',
    messagingSenderId: '224865790377',
    projectId: 'heardattack2',
    storageBucket: 'heardattack2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYUKEgqEGmMTw2RrZnFEw6VlYvYRmRbA',
    appId: '1:224865790377:ios:f3c71d9afff0dc1d477cb8',
    messagingSenderId: '224865790377',
    projectId: 'heardattack2',
    storageBucket: 'heardattack2.firebasestorage.app',
    iosBundleId: 'com.example.hackattack2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYUKEgqEGmMTw2RrZnFEw6VlYvYRmRbA',
    appId: '1:224865790377:ios:f3c71d9afff0dc1d477cb8',
    messagingSenderId: '224865790377',
    projectId: 'heardattack2',
    storageBucket: 'heardattack2.firebasestorage.app',
    iosBundleId: 'com.example.hackattack2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJXM1KUxD7_lo-fy8NSSuGzKW0GwGE-tU',
    appId: '1:224865790377:web:21e8357f993108f4477cb8',
    messagingSenderId: '224865790377',
    projectId: 'heardattack2',
    authDomain: 'heardattack2.firebaseapp.com',
    storageBucket: 'heardattack2.firebasestorage.app',
    measurementId: 'G-DBX7DYD7ZE',
  );
}
