import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hackattack2025/navigation/route.dart';
import 'package:firebase_core/firebase_core.dart'; // Import firebase_core
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI

void main() async {
  // Make main function async
  WidgetsFlutterBinding
      .ensureInitialized(); // Ensure Flutter binding is initialized
  await Firebase.initializeApp(
    // Initialize Firebase
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: AppRoutes.getRoutes(),
      title: 'Flutter Demo',
      theme: ThemeData(
        textTheme: GoogleFonts.aclonicaTextTheme()
            .apply(
              bodyColor: Colors.black,
              displayColor: Colors.black,
            )
            .copyWith(
              bodyMedium: GoogleFonts.aclonica(fontSize: 15),
            ),
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      initialRoute: AppRoutes.roleselection,
    );
  }
}
